id: I22333339
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T06:19:19+00:00'
last_modified: '2022-06-07T17:46:20.017183+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4876
  title: གསུང་འབུམ། ཆོས་གྲགས་ཡེ་ཤེས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    66DA:
      image_group_id: I1KG4878
      title: ''
      total_pages: 977
      order: 1
      base_file: 66DA.txt
    DC51:
      image_group_id: I1KG4879
      title: ''
      total_pages: 941
      order: 2
      base_file: DC51.txt
    EE0F:
      image_group_id: I1KG4880
      title: ''
      total_pages: 905
      order: 3
      base_file: EE0F.txt
    F042:
      image_group_id: I1KG4881
      title: ''
      total_pages: 941
      order: 4
      base_file: F042.txt
    '5440':
      image_group_id: I1KG4882
      title: ''
      total_pages: 973
      order: 5
      base_file: 5440.txt
    4DFB:
      image_group_id: I1KG4883
      title: ''
      total_pages: 1101
      order: 6
      base_file: 4DFB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
